name: Release Stable

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release-stable:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "22"

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: npm run lint

      - name: Run format check
        run: npm run format:check

      - name: Run tests
        run: npm run test

      - name: Build
        run: npm run prepublishOnly

      - name: Publish to NPM
        id: publish
        uses: JS-DevTools/npm-publish@v4
        with:
          token: ${{ secrets.NPM_ACCESS_TOKEN }}

      - name: Push tag
        uses: anothrNick/github-tag-action@v1
        if: steps.publish.outputs.type
        env:
          CUSTOM_TAG: v${{ steps.publish.outputs.version }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
